services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmaster_postgres
    environment:
      POSTGRES_DB: taskmaster
      POSTGRES_USER: taskmaster_user
      POSTGRES_PASSWORD: taskmaster_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmaster_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmaster_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskmaster.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - taskmaster_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  taskmaster_network:
    driver: bridge
